import "./globals.css";

import Nav from '../components/Nav/Nav';
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "The Fantasy Draft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full px-20 2xl:w-[1536px] m-auto">
        <Nav />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
