import "./globals.css";
import Nav from '../components/Nav/Nav';
import Footer from "@/components/Footer/Footer";
import Provider from "./provider";

export const metadata = {
  title: "The Fantasy Draft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-auto flex flex-col items-center max-w-[100rem]">
        <Provider>
          <div className="w-full">
            <Nav />
            <main>
              {children}
            </main>
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
